apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 100
        runAsUser: 99
        runAsGroup: 100
      containers:
      - name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:latest
        ports:
        - containerPort: 3005
          name: http
        envFrom:
        - configMapRef:
            name: audiobookshelf-config
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: metadata
          mountPath: /metadata
        - name: podcasts
          mountPath: /podcasts
        - name: audiobooks
          mountPath: /audiobooks
        - name: config
          mountPath: /config
      volumes:
      - name: metadata
        persistentVolumeClaim:
          claimName: metadata-data-pvc
      - name: podcasts
        persistentVolumeClaim:
          claimName: podcasts-data-pvc
      - name: audiobooks
        persistentVolumeClaim:
          claimName: audiobooks-data-pvc
      - name: config
        persistentVolumeClaim:
          claimName: config-data-pvc
